# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JXImageBrowser' do
    pod 'SDWebImage', '4.0.0'
#    pod 'AFNetworking', '3.0.4'
end

